// Fleet GPS Tracker
// Track fleet vehicles with GPS coordinates, speed, heading, and geofencing for transportation logistics management.
// Auto-generated by @ph-itdev/logistics-pipeline


class FleetTracker {
  constructor() { this.vehicles = new Map(); this.geofences = new Map(); this.alerts = []; }
  registerVehicle(id, name, metadata = {}) { this.vehicles.set(id, { id, name, ...metadata, position: null, speed: 0, heading: 0, history: [] }); }
  updatePosition(id, { lat, lon, speed = 0, heading = 0 }) {
    const v = this.vehicles.get(id);
    if (!v) throw new Error('Vehicle not found');
    v.position = { lat, lon, timestamp: Date.now() };
    v.speed = speed;
    v.heading = heading;
    v.history.push({ ...v.position, speed, heading });
    this._checkGeofences(id, lat, lon);
    return v;
  }
  addGeofence(id, name, { centerLat, centerLon, radiusKm }) {
    this.geofences.set(id, { id, name, centerLat, centerLon, radiusKm });
  }
  _checkGeofences(vehicleId, lat, lon) {
    for (const gf of this.geofences.values()) {
      const R = 6371;
      const dLat = (lat - gf.centerLat) * Math.PI / 180;
      const dLon = (lon - gf.centerLon) * Math.PI / 180;
      const a = Math.sin(dLat/2)**2 + Math.cos(gf.centerLat*Math.PI/180)*Math.cos(lat*Math.PI/180)*Math.sin(dLon/2)**2;
      const dist = R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
      const inside = dist <= gf.radiusKm;
      const v = this.vehicles.get(vehicleId);
      const wasInside = v._geofences?.[gf.id] ?? false;
      if (wasInside && !inside) this.alerts.push({ vehicleId, geofence: gf.name, event: 'EXIT', ts: Date.now() });
      if (!wasInside && inside) this.alerts.push({ vehicleId, geofence: gf.name, event: 'ENTER', ts: Date.now() });
      if (!v._geofences) v._geofences = {};
      v._geofences[gf.id] = inside;
    }
  }
  getVehicle(id) { return this.vehicles.get(id) || null; }
  getAllVehicles() { return [...this.vehicles.values()].map(v => ({ id: v.id, name: v.name, position: v.position, speed: v.speed })); }
  getAlerts(filter = {}) { return this.alerts.filter(a => filter.vehicleId ? a.vehicleId === filter.vehicleId : true); }
}



// ─── Error handling utilities ────────────────────────────────────────────────
class LogisticsError extends Error {
  constructor(message, code, details = {}) {
    super(message);
    this.name = 'LogisticsError';
    this.code = code;
    this.details = details;
    this.timestamp = new Date().toISOString();
  }
}

function _logisticsErrorGuard(fn, context = 'unknown') {
  return function(...args) {
    try { return fn.apply(this, args); }
    catch (e) { throw new LogisticsError(`${context}: ${e.message}`, 'OPERATION_FAILED', { args: args.length, cause: e.message }); }
  };
}


// ─── Auto-generated utility helpers ──────────────────────────────────────────
function _logisticsHelpers() {
  return {
    timestamp: () => new Date().toISOString(),
    uuid: () => 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => {
      const r = Math.random() * 16 | 0;
      return (c === 'x' ? r : (r & 0x3 | 0x8)).toString(16);
    }),
    sleep: (ms) => new Promise(r => setTimeout(r, ms)),
    retry: async (fn, maxAttempts = 3, delayMs = 1000) => {
      for (let i = 0; i < maxAttempts; i++) {
        try { return await fn(); } catch (e) { if (i === maxAttempts - 1) throw e; await new Promise(r => setTimeout(r, delayMs * (i + 1))); }
      }
    },
    clamp: (val, min, max) => Math.min(Math.max(val, min), max),
    chunk: (arr, size) => Array.from({ length: Math.ceil(arr.length / size) }, (_, i) => arr.slice(i * size, i * size + size)),
  };
}

module.exports = { FleetTracker };
